---
http_interactions:
- request:
    method: get
    uri: https://api.knackhq.com/v1/objects
    body:
      encoding: US-ASCII
      string: ''
    headers:
      X-Knack-Application-Id:
      - '123456789'
      Content-Type:
      - application/json
      X-Knack-Rest-Api-Key:
      - 123-456-789
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Origin,X-Requested-With,X-HTTP-Method-Override,Content-Type,Accept,X-Knack-Application-Id,X-Knack-REST-API-Key,Knack_Application_Id,Knack_REST_API_Key
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS, PUT, DELETE
      Content-Type:
      - text/html; charset=utf-8
      Date:
      - Wed, 11 Mar 2015 20:23:16 GMT
      P3p:
      - policyref="https://api.knackhq.com/w3c/p3p.xml", CP="IDC DSP COR ADM DEVi
        TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT", CP="CAO PSA OUR"
      Server:
      - nginx/1.4.6 (Ubuntu)
      Set-Cookie:
      - connect.sid=s%3AKDO18skdtCCO2ZSTxZveBuH7xsFqZWUT.mkUPPnv0nKMUEKPca5TGKd7%2Bl%2FflMqg8h76djjJ%2BS5o;
        Path=/; Expires=Fri, 13 Mar 2015 19:46:19 GMT; HttpOnly
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Knack-Server:
      - us-e-node-2
      Content-Length:
      - '22'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |
        Internal Server Error
    http_version:
  recorded_at: Wed, 11 Mar 2015 20:23:16 GMT
recorded_with: VCR 2.9.3
